//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int IDDH { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
    }
}
